# Generated by Django 4.2.9 on 2025-11-30 15:58

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_ciudad_perfilusuario_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=usuarios.models.perfil_imagen_upload_path),
        ),
    ]
