# Generated by ChatGPT on 2025-11-30

from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_gasto_cuenta'),
        ('ingresos', '0003_ingreso_cuenta'),
        ('cuentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_origen', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monto_destino', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tasa_manual', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=18)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_entrantes', to='cuentas.cuenta')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_salientes', to='cuentas.cuenta')),
                ('gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_generadas', to='gastos.gasto')),
                ('ingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_generadas', to='ingresos.ingreso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_cuentas', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-fecha']},
        ),
    ]
