# Generated by Django 4.2.9 on 2025-12-06 15:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ingresos', '0003_ingreso_cuenta'),
        ('gastos', '0009_migrate_lugar_to_tienda'),
        ('deudas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagodeuda',
            name='gasto_relacionado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_deuda', to='gastos.gasto'),
        ),
        migrations.AddField(
            model_name='pagodeuda',
            name='ingreso_relacionado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago_deuda', to='ingresos.ingreso'),
        ),
        migrations.AlterField(
            model_name='deuda',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pagodeuda',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
