# Generated by Django 4.2.9 on 2025-11-19 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_create_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
