# Generated by Django 4.2.9 on 2025-11-19 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
        ('gastos', '0004_gasto_cantidad_alter_gasto_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='cuentas.cuenta'),
        ),
    ]
