# Generated by Django 4.2.9 on 2025-12-05 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_transferenciacuenta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gastos', '0005_gasto_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('lugar', models.CharField(blank=True, help_text='Lugar o comercio donde se realizó la compra', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='cuentas.cuenta')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='gastos.moneda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='gasto',
            name='compra',
            field=models.ForeignKey(blank=True, help_text='Compra global a la que pertenece este gasto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gastos.compra'),
        ),
    ]
