# Generated by Django 4.2.9 on 2025-12-05 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gastos', '0006_add_compra_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto de descuento aplicado', max_digits=10),
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tiendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('nombre', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='gastos.tienda'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='tienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='gastos.tienda'),
        ),
    ]
