# Generated by Django 4.2.9 on 2025-12-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0007_gasto_descuento_tienda_compra_tienda_gasto_tienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Monto de descuento aplicado', max_digits=10),
        ),
    ]
