# Generated by Django 4.2.9 on 2025-12-05 19:24

from django.db import migrations

def migrate_lugar_to_tienda(apps, schema_editor):
    Gasto = apps.get_model('gastos', 'Gasto')
    Tienda = apps.get_model('gastos', 'Tienda')
    
    # Filter expenses that have a 'lugar' but no 'tienda'
    gastos_to_migrate = Gasto.objects.filter(tienda__isnull=True).exclude(lugar__isnull=True).exclude(lugar__exact='')
    
    for gasto in gastos_to_migrate:
        if gasto.lugar and gasto.usuario:
            # Create or get the store
            tienda, created = Tienda.objects.get_or_create(
                nombre__iexact=gasto.lugar,
                usuario=gasto.usuario,
                defaults={'nombre': gasto.lugar}
            )
            gasto.tienda = tienda
            gasto.save()

class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0008_alter_gasto_descuento'),
    ]

    operations = [
        migrations.RunPython(migrate_lugar_to_tienda),
    ]
