# Generated by Django 4.2.9 on 2025-11-19 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
        ('ingresos', '0002_alter_ingreso_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='cuentas.cuenta'),
        ),
    ]
